version: '3.8'

services:
  dockerpoc:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
    volumes:
      # Mount certificates directory for development
      - ./certs:/app/certs:ro
    user: "1000:1000"  # Use UID/GID for appuser (security)
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/home"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - app-network

networks:
  app-network:
    driver: bridge 