name: Checkov Static Code Analysis

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  checkov:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Run Checkov
      uses: bridgecrewio/checkov-action@master
      with:
        directory: .
        framework: dockerfile,kubernetes
        output_format: cli
        output_file: checkov-report.json
        soft_fail: true
        skip_check: CKV_DOCKER_2,CKV_DOCKER_8,CKV_DOCKER_10

    - name: Upload Checkov report
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: checkov-report
        path: checkov-report.json 